apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
#  - name: Tempo
#    type: tempo
#    access: proxy
#    url: http://tempo:3200
#    uid: tempo
#    jsonData:
#      tracesToLogs:
#        datasourceUid: 'loki'
#        tags: ['container']
#        filterByTraceId: true
#        filterBySpanId: false
#        mapTagNamesEnabled: false
#      tracesToMetrics:
#        datasourceUid: 'prometheus'
#        tags: [{ key: 'service.name', value: 'service' }]
#        queries:
#          - name: 'Sample Query'
#            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
#      nodeGraph:
#        enabled: true
#      serviceMap:
#        datasourceUid: 'prometheus'
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID