global:
  scrape_interval: 15s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'node'
    static_configs:
    - targets: ['nodeexporter:9100']

rule_files:
- alert_rules.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093